<a href="https://colab.research.google.com/github/raqueeb/nlp_bangla/blob/master/NLP_tokenization_unicode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## সহজ বাংলায় 'বাংলা' ন্যাচারাল ল্যাঙ্গুয়েজ প্রসেসিং (এনএলপি)

### যন্ত্রের এবং মানুষের শেখার ধারণা একই

ভালো করে লক্ষ্য করে দেখবেন যে একটা মেশিন এবং একটা বাচ্চার শেখার প্রসেস প্রায় একই। আমি আমাদের (আমার এবং স্বাতীর) বাচ্চাগুলোর উদাহরণ দেই। আমাদের বাচ্চাগুলো যখন কথা বলা শুরু করেছিল, তখন সে ভাষার কোন ধরনের গ্রামার সম্বন্ধে জানা তো দুরের কথা, তারা অক্ষরই জানতো না। তারা বিশেষ করে আমরা মানে বাবা-মা আত্মীয়-স্বজন সবার কাছ থেকে বিভিন্ন শব্দের স্যাম্পল শুনে শুনে কিছু একটা তৈরি করার চেষ্টা করত মাথার ভেতরে। তার মানে তারা শব্দগুলোকে ঠিকমত ডিকোড অর্থাৎ কোন শব্দগুলো কি, অথবা শব্দগুলো কোন অক্ষরগুলো দিয়ে তৈরি, কোনটার সাথে কোনটা লাগালে ভাব প্রকাশ হবে সেটা না বুঝেই বিভিন্ন শব্দ জোড়া লাগিয়ে কথা বলার চেষ্টা করতো। অনেক সময় সেই বাক্যগুলো মিনিংফুল হত, আবার অনেক সময় হতো না। এর অর্থ হচ্ছে একটা বাক্যে কিভাবে শব্দগুলোকে জোড়া লাগিয়ে ‘নাউন প্রনাউন ভার্ব অ্যাডযেক্টিভ’ না জেনে এমন কিছু তৈরি করত যা অনেক সময় মিলে যেত। যখন মিলত না তখন আমরা মানে মা-বাবা সেটাকে কারেকশন করে দিতাম। এরপর কয়েকদিন সে ভুলভাল বলে আস্তে আস্তে ঠিক করে নিতো তার শুরুর বাক্য তৈরি স্টাইল। আর সব কিছুই তারা করত কোন ধরনের  অক্ষর বা গ্রামার সম্বন্ধে ন্যূনতম ধারণা না নিয়েই। এটাই লক্ষ্য করার জিনিস। এবং ন্যাচারাল ল্যাঙ্গুয়েজ প্রসেসিং এ সে কারণে আমরা অক্ষর নিয়ে খুব একটা মাথা ঘামাইনা। বরং শব্দগুলোর সিকোয়েন্স ম্যাটার করে বেশি। একই শব্দ আগে পড়ে বসলে মানে পাল্টে যায়। সেটা দেখবো সামনে।

## অক্ষরজ্ঞান অথবা ব্যাকরণ শিখিয়ে এনএলপি হবে না

এতক্ষণ যা বললাম তার একটা সারমর্ম করি এখানে। একটা বাচ্চা পৃথিবীতে এলো। তার আশেপাশের সবাই কথা বলছে বিভিন্ন ভঙ্গিতে। তাকে শেখানো হয়নি ভাষার রুল গুলোকে, বরং সে মাসের-পর-মাস দেখচ্ছে তার আশেপাশের মানুষজন কিভাবে যেন যোগাযোগ বলছে। উপায়ন্তর না দেখে কোন ধরনের রুলস না জেনে মানুষ কিভাবে কথা বলছে সেই প্যাটার্ন টা বের করে আশেপাশের মানুষ গুলোকে মিমিক করে কথা বলা শুরু করেছে বাচ্চাটা। বাচ্চাটার মাথার নিউরাল নেটওয়ার্ক আশেপাশের সব কিছু প্যাটার্ন ধরে ভাষার ব্যবহার শুরু করেছে কোন নিয়ম নীতি না জেনেই।

মজার কথা হচ্ছে যখন আমি মেশিন লার্নিং এবং নিউরাল নেটওয়ার্ক নিয়ে কাজ করা শুরু করলাম, তখন বাচ্চাদের পুরো ব্যাপারটা মনে হতে থাকলো। বাচ্চাদের ছোটবেলার ব্যবহার আর নিউরাল নেটওয়ার্কের ব্যবহারের মধ্যে কোন পার্থক্য দেখি না। বড় হয়েও আমি ক্যাডেট কলেজে বাংলা গ্রামারে কোনরকমে পাস করে বের হতাম। আসলে ভাষা এমন একটা জিনিস যার জন্য কোন ধরনের কমপ্লিট ম্যানুয়াল তৈরি করা সম্ভব না, যেখানে আমরা বলতে পারি ভাষা এভাবেই হতে হবে, এর বাহিরে হলে চলবে না। ভাষায় এটা হলে বারোটা বেজে যেতো সাহিত্যের।  

সেকারণে ছোটবেলায় আমাদের বাচ্চারা যেভাবে ভাষাকে তাদের কাজের সুবিধার জন্য ব্যবহার করছিল, সেটার অ্যাকুরেসি বাড়ছিল দিন দিন আশেপাশের ফিডব্যাক এর উপর ভিত্তি করে। তার মানে ওরা মাঝে মাঝে মুখস্থ করে, মাঝেমধ্যে গোঁজামিল দিয়ে, মাসের পর মাস এই একই ধরনের রিকার্সিভ প্রসেসে একটা মানসিক মডেল তৈরি করে ফেলতো তার মাথার ভেতরে, বিশেষ করে ভাষার ব্যবহার নিয়ে। বাচ্চাদের মাথা আশেপাশের প্যাটার্ন ধরে বুঝে ফেলতো কিভাবে একটা বাক্যে কোন শব্দের পরে কোন শব্দটা আসতে পারে - বিশেষ করে কোন শব্দটা না বললেই নয়। ফলে কোন ধরনের অক্ষর বা গ্রামার না শিখেও বাচ্চারা এক ধরনের জোড়াতালি দেওয়া বাক্য তৈরি করতে পারে - যা ইমপ্রুভ করে স্কুলে ভর্তি হবার আগেই। সবচেয়ে বড় কথা হচ্ছে সেটা কাজও করে বিশেষ করে আশেপাশের মানুষগুলোর কাছে।

আর সেই কাজটাই আমি দেখছি গত কয়েক বছর ধরে ন্যাচারাল ল্যাঙ্গুয়েজ প্রসেসিং এ। ডিপ লার্নিং মডেলকে কয়েকটা শেক্সপিয়ারের নাটক দিয়ে ট্রেনিং করিয়ে দিলে, সে শেক্সপিয়ারের মত করে কাছাকাছি নাটক লিখে ফেলতে পারে। আমরা কি সেই ডিপ লার্নিং মডেলকে গ্রামার বা অক্ষর শিখিয়েছিলাম? অবশ্যই না। ডিপ লার্নিং মডেল শেক্সপিয়ারের নাটকগুলো থেকে শব্দগুলোর একটা প্যাটার্ন মানে সিকোয়েন্স ধরে ধরে বের করে সেটাকেই ব্যবহার করে জোড়াতালি দিয়ে একটা নাটক লিখেছে - যা পড়লে বোঝা যায় অনেকখানি। আর এখন এতই এতই বাক্য কম্পিউটার দেখছে, সেখানে কম্পিউটারের জন্য একটা ভালো ন্যাচারাল ল্যাংগুয়েজ প্রসেসিং মডেল তৈরি করা খুব একটা কষ্টকর নয়। সেটা আরো ভালো বোঝা যায় যখন আমরা গুগল-সার্চে বসি। কোনরকমে একটা বাক্যের প্রথম শব্দ লিখলেই হলো, সে হাজারও অপশন দিবে তার পরবর্তী শব্দটা কি হতে পারে। এটাই ন্যাচারাল ল্যাঙ্গুয়েজ প্রসেসিংয়ের একটা কাজ। আর মাথা খারাপ করবো না গল্প দিয়ে। চলুন হাতে-কলমে র অংশে।

## টোকেনাইজেশন: বাক্যকে মিনিংফুল ছোট ছোট শব্দে ভাগ

আচ্ছা বলুন তো কম্পিউটার কিভাবে আমাদের ভাষা প্রসেস করে? কম্পিউটার তো সংখ্যা ছাড়া কিছু বোঝেনা। সেখানে একটা বাক্যের ছোট ইউনিট হিসেবে শব্দ গুলোকে বলা যায় যা একেকটা অর্থ বহন করে। ভাষার একটা ছোট মিনিংফুল ইউনিট হচ্ছে শব্দগুলো। যেমন আমরা যদি একটা বাক্য না বলে শুধুমাত্র আম বলি, সেখানে একটা ধারণা পাওয়া যায় যে আমরা একটা ফলের নাম বলছি। আমরা সেই ফলটা খেতে চাচ্ছি। অথবা ফলটা আমার কাছে আছে। ভাব প্রকাশের জন্য একটা শব্দই অনেক সময় ভালো কাজ করে। আমরা শব্দগুলোকে এমনভাবে প্রসেস করব যাতে কম্পিউটার সেটাকে নিউরাল নেটওয়ার্ক পাঠাতে পারে। আমাদের নিউরাল নেটওয়ার্কের কাজ হবে শব্দগুলো থেকে তার ভাব গুলোকে বের করে নেওয়া। ন্যাচারাল ল্যাঙ্গুয়েজ প্রসেসিং এর প্রথম পার্ট হচ্ছে ভাষার নরমালাইজেশন করা। এখানে আমাদের কাজ হবে বাক্যের মধ্যে শব্দগুলোর ঠিকমতো এনকোডিং করা। একে ন্যাচারাল ল্যাঙ্গুয়েজ প্রসেসিং এর ভাষায় বলা হয় টোকেনাইজেশন। যার অর্থ হচ্ছে একটা বাক্যকে মিনিংফুল ছোট ছোট শব্দতে ভাগ করে সেটাকে সংখ্যায় এনকোড করা যা নিউরাল নেটওয়ার্ক বুঝতে পারে।

শুরুতে একটা বাচ্চা তো অক্ষর জ্ঞান নিয়ে ভাষা শেখে না। সে শেখে শব্দগুলো দিয়ে, শব্দগুলোর প্লেসমেন্ট নিয়ে, কোন শব্দ আগে পড়ে গেলে শব্দের অর্থ গুলো কি রকম হতে পারে সেটা কে বের করার চেষ্টা করে। এই একই কাজ করবে নিউরাল নেটওয়ার্ক। এখন বলি কেন অক্ষর কাজ করবে না?কারণ আমরা ছোটবেলায় অক্ষর শিখে কথা বলা শুরু করিনি। কথা বলা শুরু করেছি আশেপাশে র মানুষ থেকে শব্দ শিখে।

তবে ভাষার সবচেয়ে ছোট ইউনিট হচ্ছে একেকটা অক্ষর। কম্পিউটার সেই অক্ষর গুলো কিভাবে চেনে? অক্ষরগুলোকে একটা এনকোডিং স্কিমে ফেলে দেওয়া যায়, যার কাজ হচ্ছে অক্ষরকে সংখ্যায় পরিবর্তন করে নেওয়া। ইংরেজি শব্দের জন্য একটা পপুলার স্কিম হচ্ছে আ স্কি, বাংলা এনকোডিং এর জন্য ইউনিকোড খুব ভালো কাজ করে। কিন্তু অক্ষর দিয়ে একটা বাক্যের ভাব বোঝা যাবে?

শুরুতে **এনএলপি** এর দুটো প্রিন্সিপাল।

**১. টোকেনাইজেশন**

**২. সিকোয়েন্সিং**

## টোকেনাইজেশন, অক্ষরগুলোকে সংখ্যায় আনছি ইউনিকোডে

In [1]:
c='\u0986'
ord('অ')

2437

In [2]:
chr(2437)

'অ'

In [3]:
c='\u0986'
ord('ক')

2453

ধরুন আমরা একটা শব্দ বলছি **কলস**, এর মধ্যে তিনটা অক্ষর আছে, যাকে আলাদা করে ইউনিকোড পয়েন্ট কোড হচ্ছে নিচের লাইনে।


In [4]:
import numpy as np

np.array([ord(char) for char in u"কলস"])

array([2453, 2482, 2488])

এই একই অক্ষর দিয়ে আরেকটা শব্দ হচ্ছে **সকল**, যার মধ্যে ইউনিকোড পয়েন্ট কোড একই আছে। আগের শব্দ এবং পরের শব্দের মধ্যে সংখ্যা একই, হয়তোবা একটু একটা সামনে অথবা আর একটা পেছনে। আর এই কারনেই অক্ষর দিয়ে একটা বাক্যের সেন্টিমেন্ট বা ভাব বোঝা সম্ভব না। সে কারণে আমরা বুঝতে পারছি অক্ষরকে এনকোড না করে শব্দকে এনকোড করলে আমাদের কাজে আউটপুট আসবে।

এখানে, এনকোড ব্যাপারটাকে আমরা লেবেলিং বলতে পারি। প্রতিটা শব্দকে লেবেলিং করলে এর ভেতরে একটা প্যাটার্ন পাবো।


In [5]:
import tensorflow as tf

tf.strings.unicode_decode("সকল", input_encoding='UTF-8')

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2488, 2453, 2482], dtype=int32)>

## কি বুঝলাম অক্ষর অথবা শব্দ দিয়ে এনকোড দিয়ে?

**বাক্যের সেন্টিমেন্ট অথবা ভাবার্থ বের করার জন্য আমাদের অক্ষর এনকোড না করে শব্দকে লেবেল করতে হবে।**

ধরুন আমরা একটা বাক্য লিখছি।

**আমি ভালোবাসি বই পড়তে।** 

এটাকে এনকোড করলাম অক্ষর দিয়ে। কোন প্যাটার্ন বোঝা যায়?

না। এবং ব্যাপারটা কাজ করে না।


In [6]:
tf.strings.unicode_decode('আমি ভালবাসি বই পড়তে', 'UTF-8')

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([2438, 2478, 2495,   32, 2477, 2494, 2482, 2476, 2494, 2488, 2495,
         32, 2476, 2439,   32, 2474, 2524, 2468, 2503], dtype=int32)>

বরং এখানে আমি শব্দকে আমরা সংখ্যা '১' দিলাম। এভাবে আমরা ভালোবাসি শব্দকে '২' এবং বই '৩' শেষে 'পড়তে' শব্দকে সংখ্যাকে '৪' দিলাম।

**আমি ভালোবাসি বই পড়তে**

--> ১ ------- ২ -------- ৩ -------- ৪


এখন কিছু কোড দেখব এই ব্যাপারটা হাতে-কলমে দেখার জন্য। আমরা যেহেতু **টেন্সরফ্লো** ব্যবহার করছি সে কারণে শুরু করব এর এপিআই দিয়ে। এই এপিআই কল করব পাইথন থেকে।
 
মজার কথা হচ্ছে এই লেবেলিং করে দিচ্ছে Tokenizer নিজে থেকে। যখন আমরা Tokenizerকে ইনস্ট্যানশিয়েট করছি, সেখানে দুটো হাইপারপ্যারামিটার দিয়ে দিচ্ছি কাজের সুবিধার্থে। num_words ব্যবহার হচ্ছে সংখ্যায় - কতগুলো সবচেয়ে বেশি ব্যবহৃত শব্দগুলোকে টোকেনাইজ করতে হবে। শুরুতে ১০।

যেহেতু বাংলায় দাড়ি, । একটা আলাদা ধরনের স্টপওয়ার্ড, সেকারণে ডিফল্ট স্টপওয়ার্ড ব্যবহার না করে দাড়ি এবং ! যোগ করে দিয়েছি। বাকি সব ডিফল্ট হিসেবে ছিলো এর ভেতর। বাংলা শব্দের জন্য দিয়েছি, ইংরেজি হলে দরকার ছিলো না।

In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    'আমি ভালবাসি বই পড়তে।'
        ]

tokenizer = Tokenizer(num_words = 10, filters='!।')

ভালো করে লক্ষ্য করুন, fit_on_texts() মেথড আমাদের বাক্যকে এনকোড/লেবেলিং করে দিচ্ছে সংখ্যায়। 

আমাদের এখানে word_index মেথড ডিকশনারীর মতো জোড়া জোড়া করে কী-ভ্যালু তৈরি করে দেয় - যেখানে বাক্যের মধ্যে শব্দগুলো একটা করে কী, এর পাশে ভ্যালুটা হচ্ছে তার এসোসিয়েটেড লেবেল। 

এই ডিকশনারীটা প্রিন্ট করলেই ব্যাপারটা বোঝা যাবে।

In [8]:
tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
print(word_index)

{'আমি': 1, 'ভালবাসি': 2, 'বই': 3, 'পড়তে': 4}


In [9]:
tokenizer.num_words

10

এভাবে আমরা আরেকটা শব্দ ধরতে পারি, ধরুন, **আমি ভালোবাসি বই লিখতে**। এখন দেখুন আমরা এর মধ্যে কমন সংখ্যা **আমি ভালোবাসি বই** শব্দগুলোকে সংখ্যা ১, ২ এবং ৩ দিয়ে দিয়েছে টোকেনাইজার। এখন আমাদের বাকি থাকছে **'লিখতে'** শব্দকে নতুন একটা এনকোডিং সংখ্যা দিতে। ধরা যাক আমরা সেটাকে দিয়ে দিলাম সংখ্যা ৫। দেখুন - আমাদের টোকেনাইজারও একই কাজ করেছে।

এখন আমরা যখন দুটো শব্দের এনকোডিং/লেবেলিং দেখছি, ১২৩৪, এবং ১২৩৫, আমরা এখনই দুটি বাক্যের শব্দগুলোর মধ্যে বেশ কিছু সিমিলারিটি পাচ্ছি। কারণ এই সিমিলারিটি আমার **বইয়ের প্রতি ভালোবাসা** নিয়ে। শব্দকে একটা করে ইউনিক সংখ্যা অ্যাসাইন করে আমরা সংখ্যার মধ্যে সিমিলারিটি বুঝতে পারছি যা কম্পিউটারের জন্য বোঝা সোজা। এই শব্দকে এক একটা করে সংখ্যা দিয়ে এনকোড/লেবেলিং করাকে আমরা **টোকেনাইজেশন** বলছি। 

**আমি ভালোবাসি বই পড়তে**

--> ১ ------- ২ -------- ৩ -------- ৪

**আমি ভালোবাসি বই লিখতে**

--> ১ ------- ২ -------- ৩ -------- ৫

In [0]:
sentences = [
    'আমি ভালবাসি বই পড়তে।',
    'আমি ভালবাসি বই লিখতে!'
        ]

In [11]:
tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
print(word_index)

{'আমি': 1, 'ভালবাসি': 2, 'বই': 3, 'পড়তে': 4, 'লিখতে': 5}


word_index এখানে জোড়া জোড়া কী-ভ্যালু রিটার্ন করেছে। tokenizer সব ধরনের স্টপওয়ার্ড, মানে যতিচিহ্ন ফেলে দিয়েছে ডাটা ক্লিন রাখার জন্য।

দেখে নেই এক শব্দ কতবার ব্যবহার হয়েছে word_counts দিয়ে।

In [12]:
tokenizer.word_counts

OrderedDict([('আমি', 3), ('ভালবাসি', 3), ('বই', 3), ('পড়তে', 2), ('লিখতে', 1)])

## tokenizer এর ভেতরের কনফিগারেশন

মন ভালো হয়েছে তো এখন? tokenizer এর ভেতরে কিভাবে কাজ করছে সেটা না দেখলে আমার ঘুমই হয়না।

In [13]:
tokenizer.get_config()

{'char_level': False,
 'document_count': 3,
 'filters': '!।',
 'index_docs': '{"2": 3, "4": 2, "1": 3, "3": 3, "5": 1}',
 'index_word': '{"1": "\\u0986\\u09ae\\u09bf", "2": "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf", "3": "\\u09ac\\u0987", "4": "\\u09aa\\u09dc\\u09a4\\u09c7", "5": "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7"}',
 'lower': True,
 'num_words': 10,
 'oov_token': None,
 'split': ' ',
 'word_counts': '{"\\u0986\\u09ae\\u09bf": 3, "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf": 3, "\\u09ac\\u0987": 3, "\\u09aa\\u09dc\\u09a4\\u09c7": 2, "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7": 1}',
 'word_docs': '{"\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf": 3, "\\u09aa\\u09dc\\u09a4\\u09c7": 2, "\\u0986\\u09ae\\u09bf": 3, "\\u09ac\\u0987": 3, "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7": 1}',
 'word_index': '{"\\u0986\\u09ae\\u09bf": 1, "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf": 2, "\\u09ac\\u0987": 3, "\\u09aa\\u09dc\\u09a4\\u09c7": 4, "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7": 5

আরেকভাবে দেখি এখানে।

In [14]:
tokenizer.word_index

{'আমি': 1, 'পড়তে': 4, 'বই': 3, 'ভালবাসি': 2, 'লিখতে': 5}

এখন কর্পাস বানাবো কিভাবে? ও আচ্ছা, **কর্পাস** কি?